### ISSUE TITLE
Dex is not starting because database file cannot be opened

### ISSUE THREAD

**Issue by sebug** [f-eld-ch/sitrep#413]
**Describe the bug**
When launching the containers with the docker-compose as described in the README, all containers except the dex one come up. This means that I cannot log in after having started the UI.

**To Reproduce**
1. Create .env.local file
2. sudo docker compose --env-file .env.local up -d
3. curl http://localhost:5556 - connection refused

**Expected behavior**
docker compose up launches the containers, and after I have done the yarn start I can log in

**Logs**
Getting the logs of sitrep-dex-1 gives the following:

time="2024-08-30T09:19:17Z" level=info msg="Dex Version: v2.38.0, Go Version: go1.21.6, Go OS/ARCH: linux amd64"
time="2024-08-30T09:19:17Z" level=info msg="config using log level: debug"
time="2024-08-30T09:19:17Z" level=info msg="config issuer: http://localhost:5556/dex"
failed to initialize storage: failed to perform migrations: creating migration table: unable to open database file: no such file or directory

**Desktop (please complete the following information):**
 - OS: Ubuntu
$ uname -a
Linux esxi-ubuntu 6.8.0-40-generic 40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
Cloned commit [8c51d3d](https://github.com/f-eld-ch/sitrep/commit/8c51d3d821fc84f3f8e7372425f850c9b4f3f8fd)

**Comment by sebug** [comment]
Hello,
The reason was that the volume sitrep_dex_data could not be written to after the docker compose up. To fix I launched a new container and changed the permissions of the volume there:

sudo docker run --mount type=volume,source=sitrep_dex_data,target=/sitrepdata -it debian:latest 

and then

root@161109399eb9:/# chmod a+w sitrepdata/

I figure this doesn't happen for you because you deploy differently.

**Comment by nimdanitro** [comment]
Yes that's correct, in production setups we don't use the docker-compose with dex.

However, I also have another docker-compose for my self because I work on a SELinux enabled machine.
